//  This file was generated by CSLA Object Generator - CslaGenFork v4.3.0
//
// Filename:    NoticeColl
// ObjectType:  NoticeColl
// CSLAType:    ReadOnlyCollection

using System;
using System.Collections.Generic;
using Csla;
using Noticer.Dto;

namespace Noticer.Business
{

    /// <summary>
    /// NoticeColl (read only list).<br/>
    /// This is a generated base class of <see cref="NoticeColl"/> business object.
    /// This class is a root collection.
    /// </summary>
    /// <remarks>
    /// The items of the collection are <see cref="NoticeInfo"/> objects.
    /// </remarks>
    [Serializable]
    public partial class NoticeColl : ReadOnlyBindingListBase<NoticeColl, NoticeInfo>
    {

        #region Collection Business Methods

        /// <summary>
        /// Determines whether a <see cref="NoticeInfo"/> item is in the collection.
        /// </summary>
        /// <param name="noticeId">The NoticeId of the item to search for.</param>
        /// <returns><c>true</c> if the NoticeInfo is a collection item; otherwise, <c>false</c>.</returns>
        public bool Contains(Int64 noticeId)
        {
            foreach (var noticeInfo in this)
            {
                if (noticeInfo.NoticeId == noticeId)
                {
                    return true;
                }
            }
            return false;
        }

        #endregion

        #region Factory Methods

        /// <summary>
        /// Factory method. Loads a <see cref="NoticeColl"/> collection.
        /// </summary>
        /// <returns>A reference to the fetched <see cref="NoticeColl"/> collection.</returns>
        public static NoticeColl GetNoticeColl(string searchText)
        {
            return DataPortal.Fetch<NoticeColl>(searchText);
        }

        /// <summary>
        /// Factory method. Loads a <see cref="NoticeColl"/> collection.
        /// </summary>
        /// <returns>A reference to the fetched <see cref="NoticeColl"/> collection.</returns>
        public static NoticeColl GetNoticeColl()
        {
            return DataPortal.Fetch<NoticeColl>();
        }

        #endregion

        #region Constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="NoticeColl"/> class.
        /// </summary>
        /// <remarks> Do not use to create a Csla object. Use factory methods instead.</remarks>
        private NoticeColl()
        {
            // Prevent direct creation

            var rlce = RaiseListChangedEvents;
            RaiseListChangedEvents = false;
            AllowNew = false;
            AllowEdit = false;
            AllowRemove = false;
            RaiseListChangedEvents = rlce;
        }

        #endregion

        #region Data Access

        /// <summary>
        /// Loads a <see cref="NoticeColl"/> collection from the database.
        /// </summary>
        protected void DataPortal_Fetch(string searchText)
        {
            var args = new DataPortalHookArgs();
            OnFetchPre(args);
            using (var dalManager = DalFactoryGetManager.GetManager())
            {
                var dal = dalManager.GetProvider<INoticeCollDal>();
                var data = dal.Fetch(searchText);
                Fetch(data);
            }
            OnFetchPost(args);
        }

        /// <summary>
        /// Loads a <see cref="NoticeColl"/> collection from the database.
        /// </summary>
        protected void DataPortal_Fetch()
        {
            var args = new DataPortalHookArgs();
            OnFetchPre(args);
            using (var dalManager = DalFactoryGetManager.GetManager())
            {
                var dal = dalManager.GetProvider<INoticeCollDal>();
                var data = dal.Fetch();
                Fetch(data);
            }
            OnFetchPost(args);
        }

        /// <summary>
        /// Loads all <see cref="NoticeColl"/> collection items from the given list of NoticeDto.
        /// </summary>
        /// <param name="data">The list of <see cref="NoticeDto"/>.</param>
        private void Fetch(List<NoticeDto> data)
        {
            IsReadOnly = false;
            var rlce = RaiseListChangedEvents;
            RaiseListChangedEvents = false;
            foreach (var dto in data)
            {
                Add(NoticeInfo.GetNoticeInfo(dto));
            }
            RaiseListChangedEvents = rlce;
            IsReadOnly = true;
        }

        #endregion

        #region Pseudo Events

        /// <summary>
        /// Occurs after setting query parameters and before the fetch operation.
        /// </summary>
        partial void OnFetchPre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after the fetch operation (object or collection is fully loaded and set up).
        /// </summary>
        partial void OnFetchPost(DataPortalHookArgs args);

        #endregion

    }
}
